version: "3.6"

services:
  main:
    image: r15ch13/excavator:latest
    deploy:
      mode: global
    volumes:
      - ssh:/root/.ssh
      - main-logs:/root/log
    environment:
      GIT_USERNAME: "Richard Kuhnt"
      GIT_EMAIL: "r15ch13+git@gmail.com"
      SNOWFLAKES: "curl,openssl,brotli"
      BUCKET: "lukesampson/scoop"
      CRONTAB: "0 * * * *"
  extras:
    image: r15ch13/excavator:latest
    deploy:
      mode: global
    volumes:
      - ssh:/root/.ssh
      - extras-logs:/root/log
    environment:
      GIT_USERNAME: "Richard Kuhnt"
      GIT_EMAIL: "r15ch13+git@gmail.com"
      SNOWFLAKES:
      BUCKET: "lukesampson/scoop-extras"
      CRONTAB: "0 * * * *"
  versions:
    image: r15ch13/excavator:latest
    deploy:
      mode: global
    volumes:
      - ssh:/root/.ssh
      - versions-logs:/root/log
    environment:
      GIT_USERNAME: "Richard Kuhnt"
      GIT_EMAIL: "r15ch13+git@gmail.com"
      SNOWFLAKES:
      BUCKET: "scoopinstaller/versions"
      CRONTAB: "0 0 * * *"
  php:
    image: r15ch13/excavator:latest
    deploy:
      mode: global
    volumes:
      - ssh:/root/.ssh
      - php-logs:/root/log
    environment:
      GIT_USERNAME: "Richard Kuhnt"
      GIT_EMAIL: "r15ch13+git@gmail.com"
      SNOWFLAKES:
      BUCKET: "scoopinstaller/php"
      CRONTAB: "0 0 * * *"
  games:
    image: r15ch13/excavator:latest
    deploy:
      mode: global
    volumes:
      - ssh:/root/.ssh
      - games-logs:/root/log
    environment:
      GIT_USERNAME: "Richard Kuhnt"
      GIT_EMAIL: "r15ch13+git@gmail.com"
      SNOWFLAKES:
      BUCKET: "Calinou/scoop-games"
      CRONTAB: "0 0 * * *"
  caddy:
    image: abiosoft/caddy:no-stats
    deploy:
      mode: global
    ports:
      - "30015:2015"
    configs:
      - source: caddyfile
        target: /etc/Caddyfile
    volumes:
      - main-logs:/srv/logs/main
      - extras-logs:/srv/logs/extras
      - versions-logs:/srv/logs/versions
      - php-logs:/srv/logs/php
      - games-logs:/srv/logs/games
    environment:
      ACME_AGREE: "true"
configs:
  caddyfile:
    external: true
volumes:
  ssh:
  main-logs:
  extras-logs:
  versions-logs:
  php-logs:
  games-logs:
