name: Docker Image CI

on: [push]

jobs:

  build:

    name: Push Docker image to docker.pkg.github.com
    runs-on: ubuntu-latest
    steps:
      - name: Set selected color
        run: echo '::set-env name=SELECTED_COLOR::green'
      - name: Get color
        run: echo 'The selected color is' $SELECTED_COLOR
      - name: tr to lowercase selected color
        run: |
         repository_lower=$(echo '${{ github.repository }} | tr [:upper:] [:lower:]')
         echo '::set-env name=REPOSITORY_LOWER::$repository_lower' 
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to docker.pkg.github.com
      # https://github.com/marketplace/actions/build-and-push-docker-images#tag_with_ref
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          #repository: ${{ github.repository }}
          repository: $repository_lower
          tag_with_ref: true


#    steps:
#    - uses: actions/checkout@v2
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
